### PR TITLE
Added code owners file

### PR DESCRIPTION
**Pull request by mitchelldirt**
# CODEOWNERS File

Added the CODEOWNERS file per Ness.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by mitchelldirt — COMMENTED** [review]
Ready - file has no name 😂

**Comment by mitchelldirt** [comment]
All set

**Comment by mitchelldirt** [comment]
Please complete the quest

**Comment by mitchelldirt** [comment]
@vanessa-cooper

**Review by mitchelldirt — COMMENTED** [review]
This change is ready! Carl is out of the file

**Review by mitchelldirt — COMMENTED** [review]
Added my name

**Pull request closed without merging**
